make bn shareable when frozen
ruby/openssl pull request #808
Opened 2024-10-19 16:10 UTC by HoneyryderChuck

added frozen check on every state change.

2024-10-29 13:15 UTC, rhenium commented
Could you make the part that changes `#include <ruby/ractor.h>` a separate commit or PR?

2024-10-29 16:50 UTC, HoneyryderChuck commented
@rhenium [done](https://github.com/ruby/openssl/pull/811). I'll rebase it here once it's merged.

2024-10-29 16:50 UTC, HoneyryderChuck commented on ext/openssl/ossl_bn.c
> +	rb_check_frozen(self);			\
true, removed.

2024-11-06 13:47 UTC, HoneyryderChuck commented
@rhenium  done

2024-11-11 14:53 UTC, rhenium requested changes
`#initialize` also needs a frozen check.

Could you add a test case to ensure freezing it actually makes it shareable?

2024-11-12 11:39 UTC, HoneyryderChuck commented on ext/openssl/ossl_bn.c
> +	rb_check_frozen(self);			\
done

2024-11-12 11:40 UTC, HoneyryderChuck commented
> #initialize also needs a frozen check.

why and where? 🤔 

added a test.

2024-11-12 12:05 UTC, rhenium commented
`ossl_bn_initialize()` - it doesn't have a `rb_check_frozen(self)`.

2024-11-12 13:56 UTC, HoneyryderChuck commented
gotcha, added. One question though: is it worth it, considering that on intialize, the object isn't expected to be frozen? What would that guard against?

2024-11-13 07:25 UTC, rhenium commented
It's needed because it's callable from Ruby, especially if the object is now expected to be thread safe when frozen. Whether calling `#initialize` on a frozen object makes sense or not doesn't matter.

2024-11-13 07:25 UTC, rhenium approved these changes

2024-11-13 07:25 UTC, merged

2024-11-13 07:26 UTC, rhenium commented
It looks good to me now. Thanks!